apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultis.app.fullname" . }}
  labels:
    {{- include "vaultis.app.labels" . | nindent 4 }}
type: Opaque
data:
  NEXTAUTH_SECRET: {{ .Values.secrets.nextauthSecret | b64enc | quote }}
  NEXTAUTH_URL: {{ .Values.secrets.nextauthUrl | b64enc | quote }}
  {{- if .Values.secrets.githubId }}
  GITHUB_ID: {{ .Values.secrets.githubId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.githubSecret }}
  GITHUB_SECRET: {{ .Values.secrets.githubSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.googleId }}
  GOOGLE_ID: {{ .Values.secrets.googleId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.googleSecret }}
  GOOGLE_SECRET: {{ .Values.secrets.googleSecret | b64enc | quote }}
  {{- end }}
