{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultis.pg.fullname" . }}
  labels:
    {{- include "vaultis.pg.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.postgresql.auth.secretPasswordKey }}: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
