{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.store.name }}
  labels:
    {{- include "vaultis.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.externalSecrets.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "vaultis.serviceAccountName" . }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecretName }}
  labels:
    {{- include "vaultis.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.store.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecretName }}
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.data }}
  - secretKey: {{ .key }}
    remoteRef:
      key: {{ .name }}
  {{- end }}
{{- end }}
